### ISSUE TITLE
interface conversion: interface {} is string, not map[string]interface {}

### ISSUE THREAD

**Issue by jf87** [gtfierro/giles2#1]
Hi Gabe,

as we mailed before.
I am able to reproduce this error:
`
2016/04/25 21:54:30 http: panic serving 130.226.142.195:34052: interface conversion: interface {} is string, not map[string]interface {}
goroutine 3480 [running]:
net/http.(*conn).serve.func1(0xc840323300)
        /usr/lib/go/src/net/http/server.go:1389 +0xc1
panic(0x96b500, 0xc824c9bcc0)
        /usr/lib/go/src/runtime/panic.go:426 +0x4e9
encoding/json.(*encodeState).marshal.func1(0xc82599d7d8)
        /usr/lib/go/src/encoding/json/encode.go:266 +0x88
panic(0x96b500, 0xc824c9bcc0)
        /usr/lib/go/src/runtime/panic.go:426 +0x4e9
github.com/jf87/giles2/archiver.Dict.MarshalJSON(0xc82027f5c0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/jofu/go/src/github.com/jf87/giles2/archiver/types.go:65 +0x55c
encoding/json.marshalerEncoder(0xc8333ce0b0, 0x965a60, 0xc83f922a80, 0x195, 0x0)
        /usr/lib/go/src/encoding/json/encode.go:418 +0x159
encoding/json.(*structEncoder).encode(0xc82027f920, 0xc8333ce0b0, 0x9c2bc0, 0xc83f922a50, 0x199, 0x0)
        /usr/lib/go/src/encoding/json/encode.go:587 +0x2c4
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc8333ce0b0, 0x9c2bc0, 0xc83f922a50, 0x199, 0xc83f922a00)
        /usr/lib/go/src/encoding/json/encode.go:601 +0x51
encoding/json.(*ptrEncoder).encode(0xc820124b28, 0xc8333ce0b0, 0x9b3180, 0xc8247f5fc8, 0x196, 0x100)
        /usr/lib/go/src/encoding/json/encode.go:709 +0xea
encoding/json.(*ptrEncoder).(encoding/json.encode)-fm(0xc8333ce0b0, 0x9b3180, 0xc8247f5fc8, 0x196, 0x9b3100)
        /usr/lib/go/src/encoding/json/encode.go:714 +0x51
encoding/json.(*arrayEncoder).encode(0xc820124b30, 0xc8333ce0b0, 0x9524e0, 0xc82041a7a0, 0x97, 0xc8247f5f00)
        /usr/lib/go/src/encoding/json/encode.go:690 +0x11b
encoding/json.(*arrayEncoder).(encoding/json.encode)-fm(0xc8333ce0b0, 0x9524e0, 0xc82041a7a0, 0x97, 0x952400)
        /usr/lib/go/src/encoding/json/encode.go:697 +0x51
encoding/json.(*sliceEncoder).encode(0xc820124b38, 0xc8333ce0b0, 0x9524e0, 0xc82041a7a0, 0x97, 0x0)
        /usr/lib/go/src/encoding/json/encode.go:667 +0xb0
encoding/json.(*sliceEncoder).(encoding/json.encode)-fm(0xc8333ce0b0, 0x9524e0, 0xc82041a7a0, 0x97, 0xc82041a700)
        /usr/lib/go/src/encoding/json/encode.go:676 +0x51
encoding/json.(*encodeState).reflectValue(0xc8333ce0b0, 0x9524e0, 0xc82041a7a0, 0x97)
        /usr/lib/go/src/encoding/json/encode.go:301 +0x6b
encoding/json.(*encodeState).marshal(0xc8333ce0b0, 0x9524e0, 0xc82041a7a0, 0x0, 0x0)
        /usr/lib/go/src/encoding/json/encode.go:274 +0xa9
encoding/json.(*Encoder).Encode(0xc82599d9b0, 0x9524e0, 0xc82041a7a0, 0x0, 0x0)
        /usr/lib/go/src/encoding/json/stream.go:188 +0x94
github.com/jf87/giles2/http.(*HTTPHandler).handleSingleQuery(0xc82014ef80, 0x7f2108748d08, 0xc825efcdd0, 0xc8397ce620, 0x0, 0x0, 0x0)
        /home/jofu/go/src/github.com/jf87/giles2/http/handlers.go:141 +0x81f
github.com/jf87/giles2/http.(*HTTPHandler).(github.com/jf87/giles2/http.handleSingleQuery)-fm(0x7f2108748d08, 0xc825efcdd0, 0xc8397ce620, 0x0, 0x0, 0x0)
        /home/jofu/go/src/github.com/jf87/giles2/http/handlers.go:59 +0x5c
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc8200f86c0, 0x7f2108748d08, 0xc825efcdd0, 0xc8397ce620)
        /home/jofu/go/src/github.com/julienschmidt/httprouter/router.go:344 +0x195
net/http.(*ServeMux).ServeHTTP(0xc820013590, 0x7f2108748d08, 0xc825efcdd0, 0xc8397ce620)
        /usr/lib/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc82007e680, 0x7f2108748d08, 0xc825efcdd0, 0xc8397ce620)
        /usr/lib/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc840323300)
        /usr/lib/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2137 +0x44e
`
The issue is in types.go:65:
`cur[token].(map[string]interface{})`

If you want then you can reproduce it using this [driver.](https://github.com/jf87/smap/blob/unitoftime/python/smap/drivers/example.py) with this [config](https://github.com/jf87/smap/blob/unitoftime/python/conf/example.ini).

Then try to select tags, e.g.:
`select * where Properties/UnitofMeasure = "V"`

**Comment by gtfierro** [comment]
So the issue is the `Metadata/Location = "ITU"` inside your config file. This tells the archiver that the `Metadata/Location` is string, but then inside the driver, you make it a dict. I think this hits some race condition when I fetch records from the metadata database, so depending on which one gets loaded first, the archiver might think its a dict when its not? 

I'm not quite sure of the fix just yet, but this goes away if you take away the `Metadata/Location = "ITU"` in your config file. Also make sure to delete it from the database:

```
delete Metadata/Location where Metadata/Location = "ITU"
```

Good edge case catch! I'll try to fix this soon, but no promises until after classes are done.

**Comment by jf87** [comment]
Yes, Metadata/Location = "ITU" is the issue, but only in combination with another tag like Metadata/Location/Building = "blabla".

Now strangely the delete Metadata/Location where Metadata/Location = "ITU" works. Before, when I had by accident added Metadata/Location = "ITU" to most of my streams, it was definitely not working.
I had to go directly in MongoDB and delete manually.

Thanks!

**Comment by gtfierro** [comment]
Yes, I think I should just treat subsequent writes with that same prefix to be an overwrite.
